project:
  type: website
  output-dir: docs

website:
  title: "Sandy Beach Science"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: ISBS10
        href: isbs10/isbs10_home.qmd
      - text: Beaches for Life
        href: beachesforlife/beachesforlife.qmd
      - text: TIDELINES
        href: tidelines/tidelines.qmd
            
  sidebar:
    - id: isbs10
      style: docked
      contents:        
          - href: isbs10/isbs10_callforabstracts.qmd
          - href: isbs10/isbs10_registration.qmd
          - href: isbs10/isbs10_programme.qmd
          - href: isbs10/isbs10_workshopprep.qmd
          - href: isbs10/isbs10_proceedings.qmd
          - href: isbs10/isbs10_accommodation.qmd
          - href: isbs10/isbs10_logistics.qmd
          - href: isbs10/isbs10_tourism.qmd
          - href: isbs10/isbs10_merchandise.qmd
          - href: isbs10/isbs10_outreach.qmd
          - href: isbs10/isbs10_contactus.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

