project:
  type: website
  output-dir: docs

website:
  title: "Sandy Beach Science"
  navbar:
    pinned: true
    right:
      - text: Home
        href: index.qmd
      - text: Beaches for Life
        href: beachesforlife/bfl_home.qmd
      - text: TIDELINES
        href: tidelines/tidelines_home.qmd
      - text: Citizen science
        href: citizenscience.qmd

            
  sidebar:
    - id: beachesforlife
      style: docked
      contents:        
          - href: beachesforlife/bfl_home.qmd
            text: Project overview
          - href: beachesforlife/studyregion.qmd
            text: Study region
    - id: tidelines
      style: docked
      contents:        
          - href: tidelines/tidelines_home.qmd
            text: Project overview


format:
  html:
    toc: true
    toc-depth: 3
    toc-location: right
    theme:
      - sandstone
      - brand
    css: styles.css

editor: visual

