---
title: "Tourism information"
---

Here are some recommendations for local and national travel. Remember, South Africa does not have good public transport, so either rent a car or use platforms like Uber. South Africans drive on the left side of the road.

#### **Short trips**

**1. Safari experience**

If you have limited time but want to see something of South Africa, we recommend arriving a day or so early, hiring a car, and driving to Addo Elephant National Park (Main Camp is \~1.5h from the airport) where you can stay for a night or two. Or, if your flight arrives late in the afternoon/evening, sleep over in Port Elizabeth and head to Addo early the next day. Although not as large as Kruger National Park, Addo has the ‘big 5’ and you’re virtually guaranteed to see elephants (Hapoor Dam is one of Linda’s favourite spots in the park). You can do a day trip to Addo, but remember that the best times to see the animals are early in the morning and in the later afternoon, although you’ll still see some wildlife if you drive during the day. If you sleep over, you can join one of the game drives with a guide. We recommend driving to the park via the N2-N10.

**2. Sundays beach/Alexandria dunefield**

We’ve all read the foundational beach ecology, a lot of which came from sampling the Sundays River beach. These beautiful beaches and the largest mobile active dunefield in the southern hemisphere are a short 40 min drive from the airport. It’s a really special place to visit! Access the beach via the Pearson Park Resort (paid entry). It’s a bit cryptic to get there. Take the Colchester turn off from the N2, drive behind the petrol station and Spar shop to get onto Jetty Street. The reception is here: -33.690495, 25.828651. For the best of both worlds, spend a night at Addo, and visit Sundays on the way there or back. There is accommodation at Pearson Park Resort, and in the adjacent Colchester town.

**3. Stay in the bay**

Stay in Port Elizabeth (Humewood and Summerstrand are lovely spots with lots of accommodation) and visit the beachfront, take a boat ride with Raggy Charters to see cetaceans, seals and seabirds, dive with ProDive, or visit Sardinia Bay MPA or Maitlands beach. You could also visit SANCCOB at Cape Recife to see Critically Endangered African Penguins. For something active, the waves are generally small to surf in the bay, but are great on a good day, and there’s a very active, inclusive [open-water swimming community](https://www.facebook.com/SwimGQ/) that does group swims virtually daily from Hobie Beach year-round. People run along the beachfront all the time, most commonly in the mornings. The Boardwalk shopping centre is very popular, and there are street vendors selling curios along most of the beach front. A little further out of town is Crossways (Three Rivers Trails) and Lady’s Slipper, which are lovely spots for hikes and bike rides through the fynbos. (To hire a bicycle, reach out to one of the local bike shops, e.g. Coimbra).

**Recommended restaurants:** Most restaurants in Port Elizabeth make great food and have good service. Popular spots are Charlies, Something Good, Remos, Bocadillos, Angelos, Barneys, San Fernandos, Ginger at the Beach Hotel, De Kelder, and Hussar Grill. This is Eat! at the harbour serves fresh fish caught in the bay. Further out of town, Grass Roof is fabulous – and nice to combine with a trip to Sardinia Bay MPA or Maitlands. Crossways (half way to JBay) has a farm-kitchen restaurant, and often has markets on Sundays.

**Recommended accommodation in PE:** Humewood and Summerstrand are great suburbs to stay in. They are close to the beach, restaurants and shops, and are \<15 min from the airport. There are lots of hotels, guest houses, and BnBs where you could stay.

**4. Surf supers**

Book a shuttle (e.g. with JBay Cabs) to take you to Jeffreys Bay to surf the world-famous Supertubes for a day or two. JBay Cabs could also drop you off at Cape St Francis Resort when you’re done surfing. There is a lot of accommodation at Supertubes and in Jeffreys Bay.

#### **Make a trip of it**

**1. Garden Route road trip**

Book your long haul flight to land in Cape Town (CPT) and hire a car. Road trip from Cape Town to the conference, stopping at some of the beautiful beaches and points of interest along the Garden Route. Places like Hermanus, Cape Agulhas (southern tip of Africa), Struisbaai, De Hoop MPA, Stilbaai, Wilderness, Knysna, Plettenberg Bay, Natures Valley, and Tsitsikamma are all lovely. Alternatively, rent a car after the conference and drive back along the Garden Route to Cape Town before flying home.

**2. National Treasures**

Some of the iconic places in South Africa not already mentioned are iSimangaliso Wetland Park (Cape Vidal and Sodwana within the park are probably most easily accessible spots), Kruger National Park, Cape Town, Table Mountain National Park (including Cape Point) and Langebaan (West Coast National Park). All the national (SANParks) or provincial parks (Cape Nature, Ezemvelo) are lovely.
