---
title: "Accommodation"
---

Cape St Francis has the following accommodation options:

[Villas (4-5 bedrooms)](https://www.capestfrancis.co.za/beach-villas-accommodation-beach-break)

[Cottages (3-4 bedrooms)](https://www.capestfrancis.co.za/family-beach-cottage-accommodation-village-break)

[Apartments (1-3 bedrooms)](https://www.capestfrancis.co.za/affordable-apartment-accommodation-club-break)

The rooms are twin or double beds where you can stay on your own or share. Most rooms have en suite bathrooms; some have shared bathrooms. We will do our best to give everyone their first or second choice, but note that accommodation allocations will be on a first come (register and pay), first serve basis - so register soon to secure your ideal spot!

For those who will be sharing rooms and/or units, there will be an option in the registration form to indicate who you would like to share with. It would be very helpful if you could identify who the person/people is/are that you will share with, and then both indicate each other in the form so that we can match everyone up according to your preferences. If whole research groups would like to share one of the larger units with multiple bedrooms, please list all the people you’d like to share the unit with.

If you would like to extend your stay before or after the conference, you are welcome to book extra days at the Cape St Francis Resort. Please book this with the resort directly by email. Let them know you are part of the ISBS10 delegation to take advantage of our group rate. Note that your accommodation booking for the conference is from 20-27 June 2027.
