---
title: "Registration"
sidebar: isbs10
---

You’re advised to register and pay for the conference as soon as you are able to. This is primarily to secure your preferred type of [accommodation](isb10_accommodation.qmd), which is on a first come, first serve basis.

**Full conference registration will close on 30 April 2027. Day registration will continue to be available until 31 May 2027.**

## Full conference

**What’s included:** all meals and accommodation at Cape St Francis Resort from 20-27 June 2027; conference fees; return shuttles between PLZ airport and Cape St Francis Resort; field trip costs

- Professional (own room): R24 000

- Professional (shared room): R22 000

- Student (own room): R20 000

- Student (shared room): R18 000

## Day delegate

**What’s included:** conference fees for the day plus lunch

- Professional: R1500

- Student: R750

## Non-delegate travel companion

Although this is an academic conference, we do understand that some people may need to bring non-delegate travel companions.

**What’s included:** Dinner, bed and breakfast at at Cape St Francis Resort (including the conference dinner); return shuttles between PLZ airport and Cape St Francis Resort; field trip costs (including lunch)

- Adult (single): R15 000

- Adult (sharing): R13 000

- Child under 12 years (single): R9500

- Child under 12 years (sharing): R7500

- Child under 3 years (sharing): No cost

## Cancellation policy

- Before 1 January 2027: full refund

- 1 January 2027 – 31 March 2027: 50% refund

- After 31 March 2027: No refund

Note that there may be a delay in processing refunds.

## Conference sponsorship

We will be doing our best to raise funds to assist with the conference costs for **students and delegates from developing countries who otherwise would be unable to attend the symposium**. If successful in our fundraising efforts, we will open applications towards the end of the year. In your application, you will be asked to demonstrate what attempts you have made to secure your own funding, so please take the next few months to try and find relevant funding. Note: conference sponsorship is **not guaranteed**, will likely be limited, and you are **strongly encouraged to source your own conference funding.**
