---
title: "Logistics and arrivals"
---

#### **Arrival: shuttles to Cape St Francis Resort**

We will be offering shuttles from the Chief Dawid Stuurman/Port Elizabeth International Airport (PLZ) to Cape St Francis Resort on 20 June 2027. We will link the shuttle times with the flights landing from Johannesburg (JNB) and Cape Town (CPT) International Airports.

- It takes \~1.5h to get to the resort from PLZ airport

- Accommodation check-in opens at 2pm

- The welcome cocktail party in the evening will start at 6pm

**Please take these logistics into account when booking your flights. We recommend landing at PLZ in the early afternoon, between 12:00 and 16:00.**

#### **Departure: shuttles back to PLZ airport**

Check out is at 10:00 on 27 June 2027. If there is no one booked in your room that night, you may keep your room until departure, otherwise the resort will be able to store your luggage until you leave.

There will be shuttles departing from the resort back to PLZ airport on 27 June, **likely** at:

14:05 for the 18:05 flight to JNB (Johannesburg)

14:40 for the 18:40 flight to CPT (Cape Town)

16:35 for the 20:35 flight to CPT (Cape Town)

This is based on current flight schedules, and will be confirmed closer to the time. **If you are leaving on 27 June, we recommend booking flights departing PLZ in the evening. If you flight leaves earlier than 6pm, you are likely to miss part of the final workshop.**

If you choose to stay over and check out on 28 June, the resort has requested that you book that night’s accommodation with them directly ([please email them](https://isbs10.mandela.ac.za/Contact-us)). Check out is by 10:00. We will offer one shuttle in the morning, likely at 9:30 for the 13:30 flight to JNB (Johannesburg). **If you are leaving on 28 June and want to make use of the shuttle provided, we recommend booking flights departing PLZ no earlier than 1:30 pm.**

#### **If you extend your stay before/after ISBS10**

If you arrive earlier than 20 June 2027, you are welcome to self-drive to the resort, book a shuttle independently (we recommend JBay Cabs), or join one of the shuttles from the airport on 20 June 2027. Likewise, if you stay longer at Cape St Francis Resort after the conference, you can book a shuttle back to PLZ independently.

#### **Shuttle sign-ups**

We will post a list of shuttle times in the coming months that you can sign up for. For now, the registration form includes an indication of which day(s) you would like to use the shuttles to help us with planning.
